
steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300' # replace this value with the version that you need for your project

- script: dotnet test ./Src/TDD-Kata/Args/Args-tests-csharp/Args-tests-csharp.csproj /p:CollectCoverage=true /p:Exclude="[xunit.runner.*]*" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./Coverage/
  displayName: Run test & cover

- script: ls
  displayName: List files !

# Publish Code Coverage Results
# Publish Cobertura or JaCoCo code coverage results from a build
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: './Coverage/coverage.cobertura.xml'
    #reportDirectory: # Optional
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional
