


steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300' 

- script: dotnet build --configuration $(buildConfiguration) ./Src/TDD-Kata/Args/Args-tests-csharp/Args-tests-csharp.csproj
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    mkdir results
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  ./Src/TDD-Kata/Args/Args-tests-csharp/Args-tests-csharp.csproj /p:Exclude=[xunit.*]*
    cp $(Build.SourcesDirectory)/Src/TDD-Kata/Args/Args-tests-csharp/coverage.cobertura.xml $(Build.SourcesDirectory)/results/coverage.cobertura.xml
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
    .\tools\reportgenerator.exe -reports:$(Build.SourcesDirectory)/results/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/results/ -sourcedirs:$(Build.SourcesDirectory)/Src/TDD-Kata/Args/ -reporttypes:HTMLInline;HTMLChart
  displayName: 'Unit testing'

- task: PublishTestResults@2
  inputs:
    testRunner: xUnit
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)/results/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/results
    codecoverageTool: cobertura

- powershell: |
    Invoke-WebRequest -Uri "https://download.jetbrains.com/resharper/ReSharperUltimate.2018.3.1/JetBrains.ReSharper.CommandLineTools.2018.3.1.zip" -OutFile ".\tools\JetBrains.ReSharper.CommandLineTools.2018.3.1.zip"
    Expand-Archive -LiteralPath .\tools\JetBrains.ReSharper.CommandLineTools.2018.3.1.zip -DestinationPath .\tools\JetBrains.ReSharper.CommandLineTools
    .\tools\JetBrains.ReSharper.CommandLineTools\InspectCode.exe "$(Build.SourcesDirectory)/Src/csharp-kata.sln" -o="$(Build.SourcesDirectory)/results/inspect.xml"
  displayName: Resharper Analyse  

- script: |
    dotnet tool install dotnet-reqube --tool-path tools
    .\tools\dotnet-reqube -i "$(Build.SourcesDirectory)/results/inspect.xml" -o "$(Build.SourcesDirectory)/results/SonarQubeReport.json" -d "$(Build.SourcesDirectory)/Src/"
  displayName: 'Reqube'

- script: |
    dotnet tool install --global dotnet-sonarscanner
    dotnet sonarscanner begin /k:evilz_kata /d:sonar.organization=evilz-github /d:sonar.sources=./src /d:sonar.host.url=https://sonarcloud.io /d:sonar.pullrequest.base=master /d:sonar.pullrequest.provider=GitHub /d:sonar.pullrequest.github.repository=evilz/kata /d:sonar.externalIssuesReportPaths="$(Build.SourcesDirectory)/results/SonarQubeReport.json"  /d:sonar.login=$(sonar.token) /d:sonar.pullrequest.branch=$(System.PullRequest.SourceBranch) /d:sonar.pullrequest.key=$(System.PullRequest.PullRequestNumber)
    dotnet build --configuration $(buildConfiguration) ./Src/TDD-Kata/Args/Args-tests-csharp/Args-tests-csharp.csproj
    dotnet sonarscanner end /d:sonar.login=$(sonar.token)
  displayName: sonar PR branch $(System.PullRequest.SourceBranch) - $(System.PullRequest.PullRequestNumber)

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: ./Src/TDD-Kata/Args/Args-csharp/Args-csharp.csproj
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
