


steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300' 

- script: dotnet build --configuration $(buildConfiguration) ./Src/TDD-Kata/Args/Args-tests-csharp/Args-tests-csharp.csproj
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    mkdir results
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  ./Src/TDD-Kata/Args/Args-tests-csharp/Args-tests-csharp.csproj /p:Exclude=[xunit.*]*
    cp $(Build.SourcesDirectory)/Src/TDD-Kata/Args/Args-tests-csharp/coverage.cobertura.xml $(Build.SourcesDirectory)/results/coverage.cobertura.xml
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
    .\tools\reportgenerator.exe -reports:$(Build.SourcesDirectory)/results/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/results/ -sourcedirs:$(Build.SourcesDirectory)/Src/TDD-Kata/Args/ -reporttypes:HTMLInline;HTMLChart
  displayName: 'Unit testing'

- task: PublishTestResults@2
  inputs:
    testRunner: xUnit
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)/results/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/results
    codecoverageTool: cobertura

- script: |
    Invoke-WebRequest -Uri "https://download.jetbrains.com/resharper/ReSharperUltimate.2018.3.1/JetBrains.ReSharper.CommandLineTools.2018.3.1.zip" -OutFile ".\tools\JetBrains.ReSharper.CommandLineTools.2018.3.1.zip"
    Expand-Archive -LiteralPath .\tools\JetBrains.ReSharper.CommandLineTools.2018.3.1.zip -DestinationPath .\tools\JetBrains.ReSharper.CommandLineTools
    .\tools\JetBrains.ReSharper.CommandLineTools\InspectCode.exe $(Build.SourcesDirectory)/Src/TDD-Kata/csharp-kata.sln; -o=$(Build.SourcesDirectory)/results/inspect.xml
  displayName: Resharper Analyse  

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: ./Src/TDD-Kata/Args/Args-csharp/Args-csharp.csproj
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
